version: '3.3'
services:

  revealjs:
    build:
      context: docker
      dockerfile: Dockerfile
      #    ports:
      #      - "8000:8000"
      #      - "35729:35729"
    volumes:
      - ./slides:/revealjs/slides:ro

  nginx:
    build: ./nginx
    volumes:
      - ./slides:/srv:ro

    ports:
      - 80:80

    depends_on:
      - revealjs
